# This is a basic workflow to help you get started with Actions

name: CI Variants

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        variant: ["VariantI", "VariantII", "VariantIII", "VariantIV", "VariantV"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v4
      

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download reference drifted dataset
        run: |
          curl -L -o Base.zip https://github.com/mel361/RTDDMTFD/releases/download/v1.0-data/Base.zip
          unzip Base.zip -d ./data
          mv ./data/Base.csv ./data/Reference.csv

      - name: Download drifted dataset (Variant)
        run: |
          curl -L -o Variant.zip https://github.com/mel361/RTDDMTFD/releases/download/v1.0-data/${{ matrix.variant }}.zip
          unzip Variant.zip -d ./data
          mv "./data/${{ matrix.variant }}.csv" ./data/NewData.csv

      - name: Export variant to environment
        run: echo "VARIANT_NAME=${{ matrix.variant }}" >> $GITHUB_ENV

      - name: Run model diretory setup script
        working-directory: ./tool
        run: |
          python directory_setup.py
        
      - name: Run model training script
        working-directory: ./tool
        run: |
          python train_model.py

      - name: Run micro-batch monitoring script
        working-directory: ./tool
        run: |
          python micro-batch_monitoring_tool.py
      
      - name: Run full-batch monitoring script
        working-directory: ./tool
        run: |
          python full-batch_monitoring_tool.py

      - name: Run result comparison script
        working-directory: ./tool
        run: |
          python compare_results.py
          
      - name: Upload comparison graphs
        uses: actions/upload-artifact@v4
        with:
          name: comparisons-${{ matrix.variant }}
          path: | 
            ${{ matrix.variant }}/comparison/graphs
            ${{ matrix.variant }}/comparison/micro_batch_tool_statistics
            ${{ matrix.variant }}/comparison/full_batch_tool_statistics
            ${{ matrix.variant }}/statistics/micro_batch_tool_statistics
            ${{ matrix.variant }}/statistics/full_batch_tool_statistics
